services:
    newznabarr:
        image: riffsphereha/newznabarr
        container_name: newznabarr          
        environment:
            - FLASK_RUN_PORT=10000        
            - PUID=1000
            - PGID=1000
        volumes:
            - /path/to/config:/config              
            - /path/to/data/usenet:/data/usenet
        ports:
            - 10000:10000
        restart: unless-stopped  
        networks:
            - docker_network